# Generated by Django 3.0.1 on 2019-12-22 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizations', '0005_delete_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icao', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=20)),
                ('mf_type', models.CharField(blank=True, max_length=40, verbose_name='type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('remark', models.CharField(blank=True, max_length=120)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Airplanes.Airplane')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_role', models.CharField(blank=True, choices=[('PIC', 'Pilot'), ('SIC', 'Copilot'), ('Gast', 'Gast'), ('FI', 'Fluglehrer'), ('FE', 'Flugprüfer'), ('OTH', 'other')], max_length=4, verbose_name="pilot's role")),
                ('co_role', models.CharField(blank=True, choices=[('PIC', 'Pilot'), ('SIC', 'Copilot'), ('Gast', 'Gast'), ('FI', 'Fluglehrer'), ('FE', 'Flugprüfer'), ('OTH', 'other')], max_length=4, verbose_name="copilot's role")),
                ('attendants', models.SmallIntegerField(blank=True, null=True)),
                ('dt_offbl', models.DateTimeField(blank=True, null=True, verbose_name='off-block time')),
                ('dt_takeoff', models.DateTimeField(blank=True, null=True, verbose_name='take-off time')),
                ('dt_landing', models.DateTimeField(blank=True, null=True, verbose_name='landing time')),
                ('dt_onbl', models.DateTimeField(blank=True, null=True, verbose_name='on-block time')),
                ('pause', models.SmallIntegerField(blank=True, help_text='Time in minutes that is subtracted from the total flight time. Used when several flights are summarized in a single record.', null=True)),
                ('landings', models.SmallIntegerField(blank=True, null=True, verbose_name='number of landings')),
                ('op_time', models.IntegerField(blank=True, help_text="The airplane's operation time, used for computing flight fees. E.g. flight time in minutes, hobbs meter, tach meter, etc.", null=True)),
                ('remark', models.CharField(blank=True, max_length=120)),
                ('text_input', models.CharField(blank=True, max_length=1000)),
                ('airplane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Airplanes.Airplane')),
                ('co', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copilots', to=settings.AUTH_USER_MODEL, verbose_name='copilot')),
                ('from_af', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_airfields', to='Airplanes.Airfield', verbose_name='from')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pilots', to=settings.AUTH_USER_MODEL, verbose_name='pilot')),
                ('to_af', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_airfields', to='Airplanes.Airfield', verbose_name='to')),
            ],
        ),
    ]
