# Generated by Django 3.0.1 on 2019-12-29 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'aktiv'), ('p', 'passiv (fördernd)'), ('e', 'Ehrenmitglied'), ('o', 'other'), ('x', 'ausgeschieden')], max_length=20)),
                ('begin', models.DateField()),
                ('end', models.DateField(default=datetime.date(2999, 12, 31), editable=False)),
                ('remark', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'get_latest_by': 'begin',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('members', models.ManyToManyField(through='Organizations.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='orga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.Organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Pilot Licenses', (('SPL', 'Sailplane License'), ('PPL(A)', 'Private Pilot License (A)'), ('CPL(A)', 'Commercial Pilot License (A)'), ('ATPL', 'Air Transport Pilot License'), ('LAPL', 'Light Airplain Pilot License'), ('US-PPL', 'United States PPL'), ('UL', 'Ultralight License'))), ('Ratings', (('SEP (land)', 'CR SEP (land)'), ('SEP (sea)', 'CR SEP (sea)'), ('TMG', 'CR TMG'), ('NVFR', 'Night VFR'), ('FI SPL', 'Flight Instructor (SPL)'), ('FI TMG/SEP', 'Flight Instructor (SE, SP)'), ('winch', 'Winch'), ('tow', 'Aerotow'))), ('Radio', (('BZF1', 'BZF I'), ('BZF2', 'BZF II'), ('AZF', 'AZF'), ('L4', 'Language Proficiency L4'), ('L5', 'Language Proficiency L5'), ('L6', 'Language Proficiency L6'))), ('MED1', 'Medical Class 1'), ('MED2', 'Medical Class 2'), ('ZÜP', 'ZÜP'), ('Documents', (('ID', 'ID card'), ('passport', 'Passport'))), ('reminder', 'Reminder'), ('other', 'other')], max_length=20)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('expires', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'abilities',
                'get_latest_by': 'expires',
            },
        ),
    ]
