# Generated by Django 3.0.4 on 2020-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_membership_is_mgr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('s', 'supporting'), ('h', 'honorary'), ('o', 'other'), ('x', 'former')], max_length=20),
        ),
    ]
