# Generated by Django 2.2.7 on 2019-12-01 13:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_update_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'aktiv'), ('p', 'passiv (fördernd)'), ('e', 'Ehrenmitglied'), ('o', 'other'), ('x', 'ausgeschieden')], max_length=20)),
                ('begin', models.DateField()),
                ('end', models.DateField(default=datetime.date(2999, 12, 31), editable=False)),
                ('remark', models.CharField(blank=True, max_length=120)),
                ('orga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.Organization', verbose_name='organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'begin',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='Organizations.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
