# Generated by Django 2.2.7 on 2019-12-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_add_Membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='member',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
