# Generated by Django 3.0.3 on 2020-03-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_membership_is_mgr'),
        ('Aviation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airfield',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizations.Organization'),
        ),
    ]
